import { EditorThemeClasses } from "lexical";

export const theme: EditorThemeClasses = {
  ltr: "ltr",
  rtl: "rtl",
  placeholder: "text-gray-500",
  paragraph: "mb-4",
  quote: "border-l-4 border-blue-500 pl-4 italic text-gray-300 my-4",
  heading: {
    h1: "text-3xl font-bold mb-4 text-white",
    h2: "text-2xl font-bold mb-3 text-white",
    h3: "text-xl font-bold mb-2 text-white",
    h4: "text-lg font-bold mb-2 text-white",
    h5: "text-base font-bold mb-2 text-white",
    h6: "text-sm font-bold mb-2 text-white",
  },
  list: {
    nested: {
      listitem: "list-none",
    },
    ol: "list-decimal list-inside mb-4 pl-4",
    ul: "list-disc list-inside mb-4 pl-4",
    listitem: "mb-1",
  },
  image: "max-w-full h-auto flex justify-center align-self rounded-lg my-4",
  link: "text-blue-400 underline hover:text-blue-300",
  text: {
    bold: "font-bold",
    italic: "italic",
    overflowed: "overflow-hidden",
    hashtag: "text-blue-400",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    code: "bg-gray-700 text-green-400 px-1 py-0.5 rounded text-sm font-mono",
  },
  //   code: "bg-gray-800 text-green-400 p-4 rounded-lg my-4 overflow-x-auto font-mono text-sm",
  codeHighlight: {
    atrule: "text-purple-400",
    attr: "text-blue-400",
    boolean: "text-orange-400",
    builtin: "text-purple-400",
    cdata: "text-gray-400",
    char: "text-green-400",
    class: "text-yellow-400",
    "class-name": "text-yellow-400",
    comment: "text-gray-500",
    constant: "text-orange-400",
    deleted: "text-red-400",
    doctype: "text-gray-400",
    entity: "text-orange-400",
    function: "text-blue-400",
    important: "text-red-400",
    inserted: "text-green-400",
    keyword: "text-purple-400",
    namespace: "text-yellow-400",
    number: "text-orange-400",
    operator: "text-gray-300",
    prolog: "text-gray-400",
    property: "text-blue-400",
    punctuation: "text-gray-300",
    regex: "text-green-400",
    selector: "text-yellow-400",
    string: "text-green-400",
    symbol: "text-orange-400",
    tag: "text-red-400",
    url: "text-blue-400",

    variable: "text-orange-400",
  },
  code: "bg-gray-800 font-mono block px-2 pt-2 pb-2 pl-[52px] leading-[1.53] text-[13px] my-2 overflow-x-auto relative editorCode",
  table: "w-full border-collapse border border-gray-600 my-4",
  tableRow: "border border-gray-600",
  tableCell:
    "border border-gray-600 p-2 text-sm text-gray-200 min-w-[80px] align-top",
  tableCellHeader:
    "border border-gray-600 p-2 text-sm font-bold bg-gray-800 text-gray-100",
  tableAddRowsButton:
    "ml-2 mt-1 px-2 py-1 bg-gray-700 text-gray-200 rounded hover:bg-gray-600",
  tableAddColumnsButton:
    "ml-2 mt-1 px-2 py-1 bg-gray-700 text-gray-200 rounded hover:bg-gray-600",
  tableCellResizer: "table-cell-resizer",
  tableSelection: "table-selection",
};
